///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyAttendanceModelMessage = "message";
const String _jsonKeyAttendanceModelStatus = "status";
const String _jsonKeyAttendanceModelData = "data";
const String _jsonKeyAttendanceModelDataTotal = "total";
const String _jsonKeyAttendanceModelDataPresent = "present";
const String _jsonKeyAttendanceModelDataLate = "late";
const String _jsonKeyAttendanceModelDataAbsent = "absent";
const String _jsonKeyAttendanceModelDataHalfDay = "half_day";
const String _jsonKeyAttendanceModelDataTotalPresent = "total_present";
const String _jsonKeyAttendanceModelDataTotalLate = "total_late";
const String _jsonKeyAttendanceModelDataTotalAbsent = "total_absent";
const String _jsonKeyAttendanceModelDataTotalHalfDay = "total_half_day";

class AttendanceModelData {
  String? total;
  String? present;
  String? late;
  String? absent;
  String? halfDay;
  String? totalPresent;
  String? totalLate;
  String? totalAbsent;
  String? totalHalfDay;

  AttendanceModelData({
    this.total,
    this.present,
    this.late,
    this.absent,
    this.halfDay,
    this.totalPresent,
    this.totalLate,
    this.totalAbsent,
    this.totalHalfDay,
  });

  int? getPresent() {
    if (present != null) {
      var pr = present!.split('%');
      return double.tryParse(pr[0].toString())!.toInt();
    } else
      return 0;
  }

  int? getLate() {
    if (late != null) {
      var pr = late!.split('%');
      return double.tryParse(pr[0].toString())!.toInt();
    } else
      return 0;
  }

  int? getAbsent() {
    if (absent != null) {
      var pr = absent!.split('%');
      return double.tryParse(pr[0].toString())!.toInt();
    } else
      return 0;
  }

  int? getHalfDay() {
    if (halfDay != null) {
      var pr = halfDay!.split('%');
      return double.tryParse(pr[0].toString())!.toInt();
    } else
      return 0;
  }

  int? getInt(String? val) {
    if (val != null)
      return int.tryParse(val);
    else
      return 0;
  }

  AttendanceModelData.fromJson(Map<String, dynamic> json) {
    total = json[_jsonKeyAttendanceModelDataTotal]?.toString();
    present = json[_jsonKeyAttendanceModelDataPresent]?.toString();
    late = json[_jsonKeyAttendanceModelDataLate]?.toString();
    absent = json[_jsonKeyAttendanceModelDataAbsent]?.toString();
    halfDay = json[_jsonKeyAttendanceModelDataHalfDay]?.toString();
    totalPresent = json[_jsonKeyAttendanceModelDataTotalPresent]?.toString();
    totalLate = json[_jsonKeyAttendanceModelDataTotalLate]?.toString();
    totalAbsent = json[_jsonKeyAttendanceModelDataTotalAbsent]?.toString();
    totalHalfDay = json[_jsonKeyAttendanceModelDataTotalHalfDay]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[_jsonKeyAttendanceModelDataTotal] = total;
    data[_jsonKeyAttendanceModelDataPresent] = present;
    data[_jsonKeyAttendanceModelDataLate] = late;
    data[_jsonKeyAttendanceModelDataAbsent] = absent;
    data[_jsonKeyAttendanceModelDataHalfDay] = halfDay;
    data[_jsonKeyAttendanceModelDataTotalPresent] = totalPresent;
    data[_jsonKeyAttendanceModelDataTotalLate] = totalLate;
    data[_jsonKeyAttendanceModelDataTotalAbsent] = totalAbsent;
    data[_jsonKeyAttendanceModelDataTotalHalfDay] = totalHalfDay;
    return data;
  }
}

class AttendanceModel {
/*
{
  "message": "Attendance fetched successfully",
  "status": 200,
  "data": {
    "total": "7",
    "present": null,
    "late": null,
    "absent": null,
    "half_day": null,
    "total_present": null,
    "total_late": null,
    "total_absent": null,
    "total_half_day": null
  }
} 
*/

  String? message;
  int? status;
  AttendanceModelData? data;

  AttendanceModel({
    this.message,
    this.status,
    this.data,
  });
  AttendanceModel.fromJson(Map<String, dynamic> json) {
    message = json[_jsonKeyAttendanceModelMessage]?.toString();
    status = json[_jsonKeyAttendanceModelStatus]?.toInt();
    data = (json[_jsonKeyAttendanceModelData] != null)
        ? AttendanceModelData.fromJson(json[_jsonKeyAttendanceModelData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[_jsonKeyAttendanceModelMessage] = message;
    data[_jsonKeyAttendanceModelStatus] = status;
    if (data != null) {
      data[_jsonKeyAttendanceModelData] = this.data!.toJson();
    }
    return data;
  }
}
